development:
  adapter: postgresql
  database: personal_ss_dev
  host: localhost
  username: abhijitsinha
  password:

test:
  adapter: postgresql
  database: personal_ss_test
  host: localhost
  username: abhijitsinha
  password:
